config/routes.rb
Rails.application.routes.draw do

  root 'people#index'
  
  get 'index', to: 'page#index'
  get 'about', to: 'page#about'

  get 'people', to: 'people#index'
  get 'show_person/:id', to: 'people#show', as: 'show_person'
  get 'new_person' => 'people#new'
  post 'create_person' => 'people#create'
  get 'edit_person/:id', to: 'people#edit', as: 'edit_person'
  patch 'update_person/:id', to: 'people#update', as: 'update_person'
  delete 'delete_person/:id', to: 'people#delete', as: 'delete_person'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord

    def index
        @people = Person.all
    end
    
    def show
        @person = Person.find(params[:id])
    end
      
    def new
        @person = Person.new
    end





















end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
      @people = Person.all
  end

  def show
      @person = Person.find(params[:id])
  end

  def new
      @person = Person.new
  end

  def create
      @person = Person.new(person_params)
      if @person.save
          redirect_to people_path, :notice => "Person created!!"
      else
          render 'new'
      end
  end

  def edit
      @person = Person.find(params[:id])
  end

  def update
      @person = Person.find(params[:id])
      if @person.update_attributes(person_params)
          redirect_to people_path, :notice => "Person edited!!"
      else
          render 'edit'
      end
  end

  def delete
      @person = Person.find(params[:id])
      @person.destroy
      redirect_to people_path, :notice => "Person deleted!!"
  end

  private def person_params
      params.require(:person).permit(:title, :age, :phone, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<%= render 'partials/header' %>

<div class="people_wrapper">
  <%= yield %>
</div>

<script src="/js/dist/bundle.js"></script>
</body>
</html>

app/views/page/about.html.erb
<% content_for :title, "About" %>

<div class="welcome">
  <%= image_tag "samurai.gif" %>
</div>

app/views/page/index.html.erb
<% content_for :title, "Home" %>

<div class="welcome">
  <%= image_tag "samurai.gif" %>
</div>

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Rails Contacts App</title>
    
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

    <% if flash.any? %>
      <%= render 'partials/emssg', mssg: flash[:notice] %>
    <% end %>

    <div class="header_loggedin">
      <div class="left">
        <%= link_to "Home", root_path %>
        <%= link_to "About", about_path %>
        <%= link_to "People", people_path %>
        <%= link_to "Create Person", new_person_path %>
      </div>
    </div>

app/views/people/edit.html.erb
<% content_for :title, "Edit Person" %>

<div class="edit">

  <div class="edit_info">
    <%= image_tag  "cute.png", class: "edit_img", alt: "Your avatar" %>
    <span>Edit Person</span>
  </div>

  <%= form_for @person, url: { action: 'update' } do |f| %>

    <% if @person.errors.any? %>
      <%= render 'partials/emssg', mssg: @person.errors.full_messages[0] %>
    <% end %>

    <div class="eu_div">
      <span class='edit_span'>Name</span>
      <%= f.text_field :title, class: "e_username", placeholder: 'Name..', autofocus: true, spellcheck:false, autocomplete: false %>
    </div>
    
    <div class="eu_div">
      <span class='edit_span'>Age</span>
      <%= f.text_field :title, class: "e_username", placeholder: 'Age..', autofocus: true, spellcheck:false, autocomplete: false %>
    </div>
    
    <div class="eu_div">
      <span class='edit_span'>Phone</span>
      <%= f.text_field :title, class: "e_username", placeholder: 'Phone..', autofocus: true, spellcheck:false, autocomplete: false %>
    </div>
  
    <div class="eu_div">
      <span class='edit_span'>Email</span>
      <%= f.text_field :title, class: "e_username", placeholder: 'Email..', autofocus: true, spellcheck:false, autocomplete: false %>
    </div>


    <div class="eb_btns">
       <%= f.submit "Update Person" %>
    </div>

  <% end %>

</div>

app/views/people/index.html.erb
<% content_for :title, "Home" %>

<div class="welcome">
  <%= image_tag "samurai.gif" %>
</div>

app/views/people/new.html.erb
<% content_for :title, "View People" %>

<div class="people_wrapper">
  <div class="home">

    <div class="blog">
      <div class="blog_c">
        <span class="blog_name"><%= @person.title %></span>
        <span class="blog_age"><%= @person.age %></span>
        <span class="blog_phone"><%= @person.phone %></span>
        <span class="blog_email"><%= @person.email %></span>
      </div>
      <div class="blog_actions">
        <%= link_to "Edit", edit_person_path(@person.id), class: "sec_btn" %>
        <%=
          link_to "Delete",
          delete_person_path(@person.id),
          class: "sec_btn blog_dlt",
          :data => { :confirm => "Are you sure??" },
          :method => :delete
        %>
        <%= link_to "Back", people_path, class: 'pri_btn' %>
      </div>
    </div>

  </div>
</div>

app/views/people/show.html.erb
<% content_for :title, "View Contact" %>

<div class="people_wrapper">
  <div class="home">

    <div class="blog">
      <div class="blog_c">
      <span class="blog_name"><%= @person.title %></span>
      <span class="blog_age"><%= @person.age %></span>
      <span class="blog_phone"><%= @person.phone %></span>
      <span class="blog_email"><%= @person.email %></span>
      
      </div>
      <div class="blog_actions">
        <%= link_to "Edit", edit_person_path(@person.id), class: "sec_btn" %>
        <%=
          link_to "Delete",
          delete_person_path(@person.id),
          class: "sec_btn blog_dlt",
          :data => { :confirm => "Are you sure??" },
          :method => :delete
        %>
        <%= link_to "Back", people_path, class: 'pri_btn' %>
      </div>
    </div>

  </div>
</div>